### ISSUE TITLE
Regarding the cell to barcode dataframe for TrackerSeq data

### ISSUE THREAD

**Issue by cakeinspace** [mayer-lab/Bandler-et-al_lineage#1]
Hey is it possible to have the processed cell to barcode dataframe. From what i understand there are 1314 barcodes detected but only 260 cells. Seems kind of low but please correct me if im missing something

**Comment by mayer-lab** [comment]
Hi, the TrackerSeq dataset contains 256 multicellular clones of GABAergic neurons, which corresponds to approximately 1800 cells. Here is a download link to the processed cell to barcode data frame: https://keeper.mpdl.mpg.de/f/9b9d33a7503b4658aad1/?dl=1

**Comment by cakeinspace** [comment]
ah ok thanks a lot

**Comment by cakeinspace** [comment]
hey thanks for sharing the dataset. just a small doubt i was quickly going through the data and it appears the maximum size of a pool of multi cellular clones is 8. i was just 
<img width="391" alt="Screenshot 2022-06-01 at 22 49 22" src="https://user-images.githubusercontent.com/16275532/171498994-09b90ad9-55ef-4c0e-8db7-3c1a487f59d0.png">
counting the number of clones in each multicellular clones group and i get this kind of histogram. is this what you also get from the data and also can this method track clonal histories for longer duration of time where we capture significantly more cell divisions. On a related note the cell division is it also binary in this case.

**Comment by mayer-lab** [comment]
Yes, it looks something like this - please see Extended Data Fig. 9 from Bandler et al. 2021. 
Yes, TrackerSeq can also track clonal histories over a longer period of time and over more cell divisions, but of course that depends on the biological system and question.
